FROM postgres:18-alpine AS builder
RUN apk add --no-cache git build-base postgresql-dev
RUN git clone https://github.com/tembo-io/pgmq.git /tmp/pgmq && git -C /tmp/pgmq checkout v1.7.0
WORKDIR /tmp/pgmq/pgmq-extension
RUN make clean && make && make install

FROM postgres:18-alpine
COPY --from=builder /usr/local/lib/postgresql/ /usr/local/lib/postgresql/
COPY --from=builder /usr/local/share/postgresql/extension/ /usr/local/share/postgresql/extension/
CMD ["postgres"]