CREATE TABLE IF NOT EXISTS game_statistics (
    id SERIAL PRIMARY KEY,
    game_id INTEGER UNIQUE NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    total_stars INTEGER DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);