services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8083:80"
    volumes:
      - ./index.html:/usr/share/caddy/index.html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
  
  backend:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
    stop_grace_period: 0s
      
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql