services:
  astro:
    build: .
    ports:
      - "4321:4321"
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres"
      HOST: "0.0.0.0"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql